#!/usr/bin/env python3
"""
Script to create a test Excel file with sample data to test the upload functionality
"""

import pandas as pd
import json
from datetime import datetime

# Sample data that mimics the structure from the user's file
sample_data = {
    'Empresa_Nome': ['SA CAVALCANTE COMESTIVEIS LTDA'],
    'Filial_Code': [17],
    'Filial_Nome': ['16 - BOB´S LARANJEIRAS'],
    'Filial_Nome_Descricao': ['16 - SA CAVALCANTE COMESTIVEIS LTDA'],
    'internalId': ['1|138'],
    'companyId': [1],
    'movementId': [138],
    'branchId': [1],
    'warehouseCode': ['01'],
    'destinyWarehouseCode': ['01'],
    'customerVendorCode': ['F00227'],
    'number': ['001408'],
    'series': ['U'],
    'movementTypeCode': ['1.2.02'],
    'type': ['P'],
    'status': ['F'],
    'printed': [False],
    'documentPrinted': [False],
    'billPrinted': [False],
    'registerDate': ['2003-08-06T00:00:00-03:00'],
    'exitDate': ['2003-08-11T00:00:00-03:00'],
    'commercialRepresentativeCharge': [0],
    'paymentTermCode': [30],
    'grossValue': [232],
    'netValue': [232],
    'informedNetValue': [0],
    'otherValues': [232],
    'observation': ['PROGRAMA SOL'],
    'discountPercentage': [0],
    'expensePercentage': [0],
    'expenseValue': [0],
    'extraPercentage1': [0],
    'extraValue1': [0],
    'extraPercentage2': [0],
    'extraValue2': [0],
    'transportedProductNetWeight': [0],
    'transportedProductGrossWeight': [0],
    'financialOptionalTable1Code': ['02'],
    'financialEntryMovementId': [138],
    'netValueCurrencyCode': ['R$'],
    'date': ['2003-08-06T00:00:00-03:00'],
    'generatedEntryNumber': [1],
    'hasGeneratedBill': [False],
    'openEntryNumber': [1],
    'auxCustomerVendorCode': ['F00227'],
    'auxCustomerVendorCompanyId': [0],
    'cashAccountCode': ['02'],
    'chargePercentage': [0],
    'salesman2ChargePercentage': [0],
    'salesman3ChargePercentage': [0],
    'salesman4ChargePercentage': [0],
    'customerVendorCompanyId': [0],
    'userCode': ['cmufumba'],
    'destinyBranchId': [1],
    'fluxusGroupedFlag': [0],
    'cashAccountCompanyId': [1],
    'lotGenerated': [False],
    'accountingExportStatus': [0],
    'hasGeneratedWorkAccount': [False],
    'workAccountGenerated': [False],
    'lastEditTime': ['2003-08-11T09:08:41-03:00'],
    'indicateObjectUse': [0],
    'bonumIntegrated': [False],
    'processedFlag': [False],
    'icmsDeductionValue': [0],
    'creationUser': ['cmufumba'],
    'creationDate': ['2003-08-11T00:00:00-03:00'],
    'emailStatus': [False],
    'internalGrossValue': [232],
    'otherCompanyINSSBaseValue': [0],
    'conditionalDiscountValue': [0],
    'conditionalExpenseValue': [0],
    'affectStockOrder': [138],
    'commercialAutomationExported': [0],
    'aplicationIntegration': ['T'],
    'entryDate': ['2003-08-11T00:00:00-03:00'],
    'extemporaneous': [0],
    'merchandiseValue': [0],
    'usesFinancialValueApportionment': [False],
    'conclusionFlag': [0],
    'paradigmaStatus': ['N'],
    'paradigmaAutoIntegrated': [False],
    'originalGrossValue': [0],
    'originalNetValue': [0],
    'originalOtherValues': [0],
    'operationId': [0],
    'scpBranchId': [0],
    # JSON fields with sample data
    'movementItems': [json.dumps([{
        'companyId': 1,
        'movementId': 138,
        'sequentialId': 1,
        'sequentialNumber': 1,
        'productId': 90,
        'quantity': 4.0,
        'unitPrice': 58.0,
        'tablePrice': 0.0,
        'discountValue': 0.0,
        'registerDate': '2003-08-06T00:00:00-03:00',
        'measureUnitCode': 'GL',
        'productFantasyName': 'GALVEST BRANCO 3600 ML',
        'productCode': '01.01.0007'
    }])],
    'payments': [json.dumps([])],
    'costCenterApportionments': [json.dumps([{
        'companyId': 1,
        'apportionmentId': 7,
        'movementId': 138,
        'costCenterCode': '1.4.008',
        'value': 232.0,
        'costCenterName': 'EXPANSÃO SPC'
    }])],
    'departmentApportionments': [json.dumps([{
        'companyId': 1,
        'movementId': 138,
        'branchId': 1,
        'departmentCode': '10',
        'value': 232.0,
        'departmentName': 'OBRAS'
    }])],
    'taxes': [json.dumps([{
        'companyId': 1,
        'movementId': 138,
        'movementItemSequentialId': 0,
        'taxId': 'PIS',
        'calculationBasis': 232.0,
        'aliquot': 1.65,
        'value': 3.83,
        'calculatedCalculationBasis': 232.0,
        'edited': 0,
        'fullBase': 0.0
    }])],
    'fiscal': [json.dumps([])],
    'norm': [json.dumps([])],
    'cargoComponent': [json.dumps([])],
    'thirdPartyNF': [json.dumps([])],
    'safetyDevice': [json.dumps([])],
    'nfe': [json.dumps([])],
    'inputCTRC': [json.dumps([])],
    'outputCTRC': [json.dumps([])],
    'ctrc': [json.dumps([])],
    'transportData': [json.dumps([])],
    'documentAuthorization': [json.dumps([])],
    'judicialProcess': [json.dumps([])],
    'serviceOrder': [json.dumps([])],
    'relatedMovement': [json.dumps([])],
    'exportRelatedMovement': [json.dumps([])],
    'linkedMovement': [json.dumps([])],
    'cTe': [json.dumps([])],
    'eaiIntegration': [json.dumps([])],
    'electronicInvoiceFreeFields': [json.dumps([])]
}

if __name__ == "__main__":
    # Create DataFrame
    df = pd.DataFrame(sample_data)
    
    # Save to Excel
    filename = "test_financial_movements.xlsx"
    df.to_excel(filename, index=False)
    print(f"Test file created: {filename}")
    print(f"Data shape: {df.shape}")
    print(f"Columns: {list(df.columns)}")