"""add customer_vendor_name and cnpj to FinancialMovement

Revision ID: 80fc0baf7fe3
Revises: 
Create Date: 2025-10-27 18:52:46.020242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80fc0baf7fe3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_movement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_vendor_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('customer_vendor_cnpj', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_movement', schema=None) as batch_op:
        batch_op.drop_column('customer_vendor_cnpj')
        batch_op.drop_column('customer_vendor_name')

    # ### end Alembic commands ###
